library(dplyr)
library(tidytext)
data(stop_words)

custom_stop_words <- bind_rows(tibble(word = c('\n', 'nek', 'a', 'ahogy', 'ahol', 'aki', 'akik', 'akkor', 'alatt', 'által', 'általában', 
                                               'amely', 'amelyek', 'amelyekben', 'amelyeket', 'amelyet', 'amelynek', 'ami', 
                                               'amit', 'amolyan', 'amíg', 'amikor', 'át', 'abban', 'ahhoz', 'annak', 'arra', 
                                               'arról', 'az', 'azok', 'azon', 'azt', 'azzal', 'azért', 'aztán', 'azután', 
                                               'bár', 'be', 'belül', 'benne', 'csak', 'e', 'én', 'eddig', 'ekkor', 'el', 'elég', 'ellen', 'elő',  
                                               'éppen', 'ebben', 'ehhez', 'emilyen', 'ennek', 'erre', 'ez', 'ezt', 
                                               'ezek', 'ezen', 'ezzel', 'ezért', 'és', 'fel', 'felé', 'hanem', 'hiszen', 
                                               'hogy', 'hogyan', 'igen', 'így', 'illetve', 'ill.', 'ill', 'ilyen', 'ilyenkor', 'igy', 'ilye',
                                               'is','ison', 'ismét', 'itt', 'kell', 'kellett', 'keresztül', 
                                               'ki', 'kívül', 'között', 'közül', 'legalább', 'lehet', 'lehetett', 
                                               'legyen', 'lenne', 'lenni', 'lett', 'maga', 'magát', 'majd', 'majd', 
                                               'már', 'más', 'másik', 'meg', 'még', 'mellett', 'mert', 'mely', 'melyek', 'mi', 
                                               'mit', 'míg', 'miért', 'milyen', 'mikor', 'minden', 'mindent', 'mindenki', 
                                               'mindig', 'mint', 'mintha', 'mivel', 'ne', 
                                               'néha', 'nekem', 'neki', 'néhány', 'olyan', 'ott', 'de', 'hát', 'nagyon', 'egyébként',
                                               'össze', 'ő', 'ők', 'őket', 'pedig', 'persze', 'rá', 's', 'saját', 
                                               'sok', 'sokat', 'sokkal', 'számára', 'szemben', 'szerint', 'szinte', 'talán', 
                                               'tehát', 'teljes', 'tovább', 'továbbá', 'több', 'úgy', 'ugyanis', 
                                               'vagy', 'vagyis', 'valaki', 'valami', 'valamint', 
                                               'való', 'vagyok', 'van', 'vannak', 'volt', 'voltam', 'voltak', 'voltunk', 'vissza', 
                                               'vele', 'volna', 'úgyhogy','azaz', 'ha', 'esetén','során', 'óta', 'hogyha', 'szóval', 'tök', 'igazából',
                                               'oké', 'ezeket', 'le', 'addig', 'ebből', 'egy', 'tényleg', 'lesz', 'akár', 'sem',
                                               'valamit', 'valamilyen', 'utána', 'például', 'fog', 'tökre', 'mind', 'hozzá', 'amik', 'amiben',
                                               'abból', 'amúgy', 'kb', 'túl', 'ja', 'ugye', 
                                               'tudom', 'tudunk', 'nyílván', 'nincs', 'közben', 'tud', 'nagy', 'egész',
                                               'kicsi', 'valahogy', 'oda', 'inkább', 'egyik', 'kriszti', 'aha', 'után', 'legalábbis', 'alapvetően',
                                               'valahol', 'szempontból', 'na', 'egyáltalán', 'se', 'mik', 'hmm', 'ebbe', 'azokat', 'te', 'mindenképp','mindenféle',
                                               'izé', 'azóta', 'stb', 'kb', 'kábé', 'onnan', 'olyat', 'olivér', 'fel', 'ilyenek', 'áron',
                                               'erről', 'amiket','mondjuk', 'szerintem',
                                               '10', '10.000', '', '100', '1000', '15', '2', '20', '200', '2004', '2007',
                                               '3','30', '4', '5', '500', '5000', '90', '√°', '6', '7', '8', '8000', 'á', "22",
                                               '16', '17', '18',
                                               'andrás', 'kvázi', 'egyfajta', 'gel',
                                               "1", "1,5", "8,5", "9" , "9,45" , "9,5" , "11", "12", "13", "14", "19", "21", "24", 
                                               "24,7", "25", "27", "29", "31", "33", "37", "39", "40", "50","51", "52", "60", "65",
                                               "70", "80", "85", "86", "95", "120", "130", "140", "150", "160", "250", "260",
                                               "270", "300", "350", "365", "380", "400", "600", "650", "700", "720", "800", "900", "950",
                                               "1997", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2022", "2025", "3000", "6000",
                                            "nyilván", 'csomó', 'vagyunk', 'mondom', 'dolog'
                                               ,"fél", '400.000','nem', 'napig', 'ezeknek', 'amellett', 'istennek', 'hiszed', 'szólva', 'röviden', 'Igen', ',Igen', 'de', 'nevet',
                                            '123.',
                                            'akkor', 'de', 'és', 'Ez', 'hát', 'Is', 'lehet', 'nincs', 'Szerigy', '0-ás', '1.', 
                                            '10.', '100.', '11.', '12.', '15.', '18.', '1997-es','20%-os', '2013.', '2017.', '2018-as', '2018.',
                                            '2020-as', '2020.', '21.', '22.', '25-ei', '25-i', '25.', '27.', '3.', '4.', '52.', '7.', '95.', 'a-a', 'mond', 'gondol',
                                            'hát', 'ás', 'úgymond'
                                            ),
                                      lexicon = c("custom")),
                               stop_words)
custom_stop_words
